import Navbar from '@/components/ui/Navbar';
import Footer from '@/components/ui/Footer';

export default function Home() {
    return (
      <>
        <div className="relative min-h-screen text-white font-lexend-regular bg-black">
          <Navbar />
  
          {/* Main Content Area - Updated for Privacy Policy */}
          <main className="max-w-4xl mx-auto py-16">
            {/* Center the title and add divider */}
            <div className="text-center mb-12">
              <h1 className="text-5xl sm:text-6xl text-white font-lexend-bold mb-4">
                Privacy Policy
              </h1>
              
              <p className="text-md text-gray-400 mb-6 font-lexend-regular">
                Last updated: November 24, 2024
              </p>

              {/* Light horizontal line */}
              <div className="w-full h-[1px] bg-gray-800 mt-8"></div>
            </div>

            <div className="space-y-8 font-lexend-regular">
              <p className="text-gray-300">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              <br></br>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
  
              <h2 className="text-2xl font-lexend-bold mb-6">
                Interpretation and Definitions
              </h2>
  
              <h3 className="text-xl font-lexend-bold mb-4">
                Interpretation
              </h3>
  
              <p className="text-gray-300">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>
  
              <h3 className="text-xl font-lexend-bold mb-4">
                Definitions
              </h3>
  
              <p className="text-gray-300 mb-4">
                For the purposes of this Privacy Policy:
              </p>
  
              <ul className="list-disc pl-6 mb-6 text-gray-300 space-y-2">
                <li><strong className="font-lexend-bold">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong className="font-lexend-bold">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong className="font-lexend-bold">Application</strong> refers to Friday, the software program provided by the Company.</li>
                <li><strong className="font-lexend-bold">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to [Legal Company Name], [Legal company address].</li>
                <li><strong className="font-lexend-bold">Country</strong> refers to: New York, United States</li>
                <li><strong className="font-lexend-bold">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong className="font-lexend-bold">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong className="font-lexend-bold">Service</strong> refers to the Application.</li>
                <li><strong className="font-lexend-bold">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                <li><strong className="font-lexend-bold">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong className="font-lexend-bold">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
  
              <h2 className="text-2xl font-lexend-bold mb-6">
                Collecting and Using Your Personal Data
              </h2>

              <h3 className="text-xl font-lexend-bold mb-4">
                Types of Data Collected
              </h3>

              <h4 className="text-lg font-lexend-bold mb-3">
                Personal Data
              </h4>

              <p className="text-gray-300 mb-4">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              </p>

              <ul className="list-disc pl-6 mb-6 text-gray-300 space-y-2">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Usage Data</li>
              </ul>

              <h4 className="text-lg font-lexend-bold mb-3">
                Usage Data
              </h4>

              <p className="text-gray-300 mb-4">
                Usage Data is collected automatically when using the Service.
              </p>

              <p className="text-gray-300 mb-4">
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>

              <p className="text-gray-300 mb-4">
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              </p>

              <h2 className="text-2xl font-lexend-bold mb-6">
                Use of Your Personal Data
              </h2>

              <p className="text-gray-300 mb-4">
                The Company may use Personal Data for the following purposes:
              </p>

              <ul className="list-disc pl-6 mb-6 text-gray-300 space-y-2">
                <li><strong className="font-lexend-bold">To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                <li><strong className="font-lexend-bold">To manage Your Account</strong>: to manage Your registration as a user of the Service.</li>
                <li><strong className="font-lexend-bold">For the performance of a contract</strong>: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                <li><strong className="font-lexend-bold">To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                <li><strong className="font-lexend-bold">To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
                <li><strong className="font-lexend-bold">For business transfers</strong>: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                <li><strong className="font-lexend-bold">For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns.</li>
              </ul>

              <p className="text-gray-300 mb-4">
              All the above categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.
              </p>

              <h2 className="text-2xl font-lexend-bold mb-6">
                Retention of Your Personal Data
              </h2>

              <p className="text-gray-300 mb-4">
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
              </p>

              <p className="text-gray-300 mb-4">
                The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
              </p>

              <h2 className="text-2xl font-lexend-bold mb-6">
                Security of Your Personal Data
              </h2>

              <p className="text-gray-300 mb-4">
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </p>

              <h2 className="text-2xl font-lexend-bold mb-6">
                Google Workspace API Data Usage
              </h2>

              <p className="text-gray-300 mb-4">
                When you connect your Google Workspace account to our Service, we want to be clear about how we handle your data:
              </p>

              <ul className="list-disc pl-6 mb-6 text-gray-300 space-y-2">
                <li>We do not use Google Workspace API data to develop, improve, or train generalized/non-personalized artificial intelligence (AI) or machine learning (ML) models.</li>
                <li>Any AI features in our Service that interact with your Google Workspace data are strictly personalized to your account and your data remains private to you.</li>
                <li>When we transfer Google Workspace data to third-party services (such as for email processing or analysis), it is solely for providing our Service's functionality to you, not for training generalized AI/ML models.</li>
                <li>We maintain strict data isolation practices to ensure your Google Workspace data is only used for the specific purposes you've authorized.</li>
              </ul>

              <p className="text-gray-300 mb-4">
                We are committed to protecting your privacy and maintaining compliance with Google's API Services User Data Policy. Your Google Workspace data is only used to provide you with our Service's features and functionality.
              </p>

              <h2 className="text-2xl font-lexend-bold mb-6">
                Children's Privacy
              </h2>

              <p className="text-gray-300 mb-4">
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
              </p>

              <h2 className="text-2xl font-lexend-bold mb-6">
                Links to Other Websites
              </h2>

              <p className="text-gray-300 mb-4">
                Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
              </p>

              <p className="text-gray-300 mb-4">
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
              </p>

              <h2 className="text-2xl font-lexend-bold mb-6">
                Changes to this Privacy Policy
              </h2>

              <p className="text-gray-300 mb-4">
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
              </p>

              <p className="text-gray-300 mb-4">
                We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
              </p>

              <p className="text-gray-300 mb-4">
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
              </p>

              <h2 className="text-2xl font-lexend-bold mb-6">
                Contact Us
              </h2>

              <p className="text-gray-300 mb-4">
                If you have any questions about this Privacy Policy, You can contact us: <a href="mailto:founders@relevancy.ai" className="underline hover:opacity-80">founders@relevancy.ai</a>
              </p>
            </div>
          </main>
  
          <Footer />
        </div>
      </>
    );
  }