'use client';
import Navbar from '@/components/ui/Navbar';
import Footer from '@/components/ui/Footer';
import ScrollProgress from "@/components/magicui/scroll-progress";

export default function Home() {
    return (
      <>
        <div className="relative min-h-screen text-white font-lexend-regular bg-black">
          <Navbar />
          <ScrollProgress className="top" />
          
          {/* Main Content Area - Updated for Privacy Policy */}
          <main className="max-w-4xl mx-auto py-16">
            {/* Center the title and add divider */}
            <div className="text-center mb-12">
              <h1 className="text-5xl sm:text-6xl text-white font-lexend-bold mb-4">
                Example Blog
              </h1>
              
              <p className="text-md text-gray-400 mb-6 font-lexend-regular">
                Last updated: December 29, 2024
              </p>

              {/* Light horizontal line */}
              <div className="w-full h-[1px] bg-gray-800 mt-8"></div>
            </div>

            <div className="space-y-8 font-lexend-regular">
              <p className="text-gray-300">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              </p>
              <h2 className="text-2xl font-lexend-bold mb-6">
                Lorem ipsum dolor sit amet
              </h2>
  
              <h3 className="text-xl font-lexend-bold mb-4">
                Lorem ipsum dolor sit amet
              </h3>
  
              <p className="text-gray-300">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>
  
              <h3 className="text-xl font-lexend-bold mb-4">
                Lorem ipsum dolor sit amet
              </h3>
  
              <p className="text-gray-300 mb-4">
                Lorem ipsum dolor sit amet
              </p>
  
              <ul className="list-disc pl-6 mb-6 text-gray-300 space-y-2">
                <li><strong className="font-lexend-bold">Lorem ipsum dolor sit amet</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong className="font-lexend-bold">Lorem ipsum dolor sit amet</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong className="font-lexend-bold">Lorem ipsum dolor sit amet</strong> refers to Friday, the software program provided by the Company.</li>
                <li><strong className="font-lexend-bold">Lorem ipsum dolor sit amet</strong> refers to [Legal Company Name], [Legal company address].</li>
                <li><strong className="font-lexend-bold">Country</strong> refers to: New York, United States</li>
                <li><strong className="font-lexend-bold">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong className="font-lexend-bold">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong className="font-lexend-bold">Service</strong> refers to the Application.</li>
                <li><strong className="font-lexend-bold">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                <li><strong className="font-lexend-bold">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong className="font-lexend-bold">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </div>
          </main>
  
          <Footer />
        </div>
      </>
    );
  }